/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as MapRouteImport } from './routes/map'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartiesIndexRouteImport } from './routes/parties.index'
import { Route as PartiesIdRouteImport } from './routes/parties.$id'
import { Route as PartiesNewRouteImport } from './routes/parties.new'
import { Route as PostsNewRouteImport } from './routes/posts.new'
import { Route as ProtestsIndexRouteImport } from './routes/protests.index'
import { Route as ProtestsIdRouteImport } from './routes/protests.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIndexRoute = PartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/parties/$id',
  path: '/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesNewRoute = PartiesNewRouteImport.update({
  id: '/parties/new',
  path: '/parties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtestsIndexRoute = ProtestsIndexRouteImport.update({
  id: '/protests/',
  path: '/protests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtestsIdRoute = ProtestsIdRouteImport.update({
  id: '/protests/$id',
  path: '/protests/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/new': typeof PartiesNewRoute
  '/posts/new': typeof PostsNewRoute
  '/protests/$id': typeof ProtestsIdRoute
  '/parties/': typeof PartiesIndexRoute
  '/protests/': typeof ProtestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/new': typeof PartiesNewRoute
  '/posts/new': typeof PostsNewRoute
  '/protests/$id': typeof ProtestsIdRoute
  '/parties': typeof PartiesIndexRoute
  '/protests': typeof ProtestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/new': typeof PartiesNewRoute
  '/posts/new': typeof PostsNewRoute
  '/protests/$id': typeof ProtestsIdRoute
  '/parties/': typeof PartiesIndexRoute
  '/protests/': typeof ProtestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feed'
    | '/map'
    | '/news'
    | '/pricing'
    | '/profile'
    | '/parties/$id'
    | '/parties/new'
    | '/posts/new'
    | '/protests/$id'
    | '/parties/'
    | '/protests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed'
    | '/map'
    | '/news'
    | '/pricing'
    | '/profile'
    | '/parties/$id'
    | '/parties/new'
    | '/posts/new'
    | '/protests/$id'
    | '/parties'
    | '/protests'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/feed'
    | '/map'
    | '/news'
    | '/pricing'
    | '/profile'
    | '/parties/$id'
    | '/parties/new'
    | '/posts/new'
    | '/protests/$id'
    | '/parties/'
    | '/protests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  MapRoute: typeof MapRoute
  NewsRoute: typeof NewsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  PartiesIdRoute: typeof PartiesIdRoute
  PartiesNewRoute: typeof PartiesNewRoute
  PostsNewRoute: typeof PostsNewRoute
  ProtestsIdRoute: typeof ProtestsIdRoute
  PartiesIndexRoute: typeof PartiesIndexRoute
  ProtestsIndexRoute: typeof ProtestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/': {
      id: '/parties/'
      path: '/parties'
      fullPath: '/parties/'
      preLoaderRoute: typeof PartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/parties/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/new': {
      id: '/parties/new'
      path: '/parties/new'
      fullPath: '/parties/new'
      preLoaderRoute: typeof PartiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protests/': {
      id: '/protests/'
      path: '/protests'
      fullPath: '/protests/'
      preLoaderRoute: typeof ProtestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protests/$id': {
      id: '/protests/$id'
      path: '/protests/$id'
      fullPath: '/protests/$id'
      preLoaderRoute: typeof ProtestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  MapRoute: MapRoute,
  NewsRoute: NewsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  PartiesIdRoute: PartiesIdRoute,
  PartiesNewRoute: PartiesNewRoute,
  PostsNewRoute: PostsNewRoute,
  ProtestsIdRoute: ProtestsIdRoute,
  PartiesIndexRoute: PartiesIndexRoute,
  ProtestsIndexRoute: ProtestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
